# Basic
name:               "MYoung | 卖羊"
title:

author:
  facebook:         myangxudong
  youtubeUser:      
  youtubeChannel:   
  twitter:          myangxudong
  github:           "0237"
  stackoverflow:    
  quora:            
  linkedin:         yangxudong
  pinterest:        
  googlePlus:       
  instagram:        myangxudong
  reddit:           
  medium:           
  tumblr:           
  email:            XD_Yang@outlook.com
  weibo:            "847780848"
  wechat:           XD_Young
  qzone:            "847780848"

copyright:
  year:             2017
  name:             MYoung

permalink: none
description: > # this means to ignore newlines until "baseurl:"
  记录 coding 生活
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://myoung.me" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed